clear all;
clc;
n=15000;
k =7;
% PType=zeros(n,1);
% PType(1:n/2)=rand(n/2,1);
% PType((n/2)+1:end)=1-PType(1:n/2);
X=[ones(n,1) 25*rand(n,k-1)];
% X(:,end) = [];
% y = PType.*(X*ones(k,1)+2*randn(n,1));
y = X*ones(k,1)+2*randn(n,1);
[beta,~,~,~,stats]=regress(y,X);
true_parms = [ones(k,1);2];
regress_output = [beta;sqrt(stats(4))];
o2=optimset('Disp','Iter','MaxFunEvals',2000000,'MaxIter',15000);
o3=optimset('Disp','Iter','MaxFunEvals',2000000,'MaxIter',15000,'GradObj','on','DerivativeCheck','on');
[b1,~,~,o]=fminsearch('wageMLE',rand(k+1,1),o2,y,X);
[b2,l,e,o,g,h]=fminunc('wageMLE',2*rand(k+1,1),o2,y,X);
se2A = sqrt(diag(inv(h)));
se2B = sqrt(diag(inv(g*g')));
my_answers = b1;
